---
active_modules: [pygments, tags, blog, disqus, latex, videos]
author: David Halter
canonical_url: http://jedidjah.ch/code/
modules:
    pygments:
        style: tango
    disqus:
        shortname: jedidjah
language: en
